name: app_sena
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/arien.jpeg
    - lib/assets/images/entrada.jpeg
    - lib/assets/images/filtro.jpeg
    - lib/assets/images/login.png
    - lib/assets/images/logo.jpeg
    - lib/assets/images/ref.jpeg
    - lib/assets/images/terreno.jpeg
    - lib/assets/images/venta.jpeg
    - lib/assets/images/muebles.jpeg
    

