name: app_sena
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic

  assets:
    - assets/images/arien.jpeg
    - assets/images/entrada.jpeg
    - assets/images/filtro.jpeg
    - assets/icons/login.png
    - assets/icons/user.png
    - assets/images/logo.jpeg
    - assets/images/ref.jpeg
    - assets/images/terreno.jpeg
    - assets/images/venta.jpeg
    - assets/images/muebles.jpeg
    - assets/images/seacherwithhouse.png
